on: [ "push", "pull_request" ]

name: "Run tests"

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11.0 ]
#        os: [ macos-11.0 ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-tush
        with:
          path: soft/tush
          key: ${{ runner.os }}-tush-2

      - name: "run tests"
        run: |
          ./makesure_stable tested ; echo "exit code=$?"
