on: [ "push", "pull_request" ]

name: "Run tests"

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-tush
        with:
          path: soft/tush
          key: ${{ runner.os }}-tush-2

      - name: "run tests"
        run: |
          ./makesure_stable tested
