on: [ "push", "pull_request" ]

name: "Run tests"

jobs:
  nix:
    name: "Run tests *nix / all awks"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11.0 ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-soft
        with:
          path: soft
          # key: ${{ runner.os }}-soft
          key: ${{ matrix.os }}-soft--all

      - name: "run tests"
        run: |
          ./makesure_stable tested_awks

  macos_gawk:
    name: "Run tests macos / gawk"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-10.15, macos-11.0 ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-soft
        with:
          path: soft
          key: ${{ matrix.os }}-soft--macos-gawk

      - name: "run tests"
        run: |
          brew install gawk # TODO understand if this step can be cached
          ./makesure_stable
          
  win:
    name: "Run tests Win"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2016, windows-2019, windows-2022 ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-soft
        with:
          path: soft
          key: ${{ matrix.os }}-soft--win

      - name: "run tests"
        run: |
          & bash -e -c "./makesure_stable"

