on: [ "push", "pull_request" ]

name: "Run tests"

jobs:
#  nix:
#    name: "Run tests *nix"
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11.0 ]
#    steps:
#      - uses: actions/checkout@v2
#
#      - uses: actions/cache@v2
#        id: cache-tush
#        with:
#          path: soft/tush
#          key: ${{ runner.os }}-tush-2
#
#      - name: "run tests"
#        run: |
#          ./makesure_stable ; echo "exit code=$?"
  win:
    name: "Run tests Win"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019 ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-tush
        with:
          path: soft/tush
          key: ${{ runner.os }}-tush-2

      - name: "run tests"
        run: |
          & "C:\Program Files\Git\bin\bash.exe" -c 'echo git bash 111; exit 111' ; echo $LASTEXITCODE
          & "C:\Program Files\Git\bin\bash.exe" -c 'echo git bash 0; exit 0' ; echo $LASTEXITCODE
          & "C:\Program Files\Git\bin\sh.exe" -c 'echo git sh 111; exit 111' ; echo $LASTEXITCODE
          & "C:\Program Files\Git\bin\sh.exe" -c 'echo git sh 0; exit 0' ; echo $LASTEXITCODE
          & bash -c 'echo bash 111; exit 111' ; echo $LASTEXITCODE
          & bash -c 'echo bash 0; exit 0' ; echo $LASTEXITCODE
          & where.exe bash
          & bash -c 'exit 1'
